services:
  pg_auth:
    image: postgres:17.2-alpine3.21
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_users_volume:/var/lib/postgresql/data

volumes:
  postgres_users_volume: